# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x65tection.proto\x12\tdetection\"B\n\x0c\x46rameRequest\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\r\n\x05\x66rame\x18\x03 \x01(\x0c\"t\n\rTrackedObject\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\n\n\x02x1\x18\x03 \x01(\x02\x12\n\n\x02y1\x18\x04 \x01(\x02\x12\n\n\x02x2\x18\x05 \x01(\x02\x12\n\n\x02y2\x18\x06 \x01(\x02\x12\x10\n\x08track_id\x18\x07 \x01(\x05\"|\n\x11\x41nnotatedResponse\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x17\n\x0f\x61nnotated_frame\x18\x03 \x01(\x0c\x12)\n\x07objects\x18\x04 \x03(\x0b\x32\x18.detection.TrackedObject2]\n\x10\x44\x65tectionService\x12I\n\x0cStreamFrames\x12\x17.detection.FrameRequest\x1a\x1c.detection.AnnotatedResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMEREQUEST']._serialized_start=30
  _globals['_FRAMEREQUEST']._serialized_end=96
  _globals['_TRACKEDOBJECT']._serialized_start=98
  _globals['_TRACKEDOBJECT']._serialized_end=214
  _globals['_ANNOTATEDRESPONSE']._serialized_start=216
  _globals['_ANNOTATEDRESPONSE']._serialized_end=340
  _globals['_DETECTIONSERVICE']._serialized_start=342
  _globals['_DETECTIONSERVICE']._serialized_end=435
# @@protoc_insertion_point(module_scope)
